### ISSUE TITLE
NPM publish trigger on published draft releases.

### ISSUE THREAD

**Issue by Jeadie** [spiceai/spice.js#103]
Expected this trigger to run on a draft release that has been published
```yaml
on:
  release:
    types: [created]
```
DId not occur.
